'use strict';
const width = 5;
const height = 6;
const area = width * height;
console.log('value of area', area);
console.log('typeof area', typeof area);
const bill = 5;
const payment = 10;
const change = payment - bill;
console.log('value of change', change);
console.log('typeof change', change);
const quizzes = 5;
const midterm = 7;
const final = 4;
const grade = (quizzes + midterm + final) / 3;
console.log('vlaue of grade', grade);
console.log('typeof grade', typeof grade);
const firstName = 'Bryant';
const lastName = 'Mendoza';
const fullName = firstName + ' ' + lastName;
console.log('value of fullName', fullName);
console.log('typeof fullName', typeof fullName);
const ph = 5;
const isAcidic = ph < 7;
console.log('value of isAcidic', isAcidic);
console.log('typeof isAcidic', typeof isAcidic);
const headCount = 300;
const isSparta = headCount === 300;
console.log('value of isSparta', isSparta);
console.log('typeof isSparta', typeof isSparta);
let motto = fullName;
motto += ' ' + 'is' + ' ' + 'the' + ' ' + 'GOAT';
console.log('value of motto', motto);
console.log('typeof motto', typeof motto);
